name: CI
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i -g npm@8.3.1
      - run: npm run setup

  dependabot:
    name: 'Dependabot'
    permissions:
      pull-requests: write
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Auto-merge Dependabot PRs for semver-patch updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: |
          gh pr edit "$PR_URL" --add-label "security-update"
          gh pr comment "$PR_URL" --body "This is a semver-patch version update. It will be auto-merged."
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-approve Dependabot PRs for semver-minor updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: |
          gh pr edit "$PR_URL" --add-label "security-update"
          gh pr comment "$PR_URL" --body "This is a semver-minor version update."
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-label Dependabot PRs for semver-major updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-major'}}
        run: |
          gh pr edit "$PR_URL" --add-label "security-update"
          gh pr comment "$PR_URL" --body "This is a semver-major version update. Please review the changes manually! :)"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-label Dependabot PRs for unknown updates
        if: ${{steps.metadata.outputs.update-type == 'null'}}
        run: |
          gh pr edit "$PR_URL" --add-label "security-update"
          gh pr comment "$PR_URL" --body "This is an unknown version update. Please review the changes manually! :)"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

